version: "3.1"
services:

  task-tracker-backend:
    container_name: "task-tracker-scheduler"
    image: task-tracker-scheduler:0.0.1
    networks:
      - task-tracker-service-discovery_task-tracker-network
    build:
      context: ../task-tracker-scheduler/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:8083"

networks:
  task-tracker-service-discovery_task-tracker-network:
    external: true