spring:
  config:
    activate:
      on-profile: ide

  datasource:
    url: jdbc:postgresql://localhost:15432/task-tracker-backend
    username: admin
    password: admin

#  flyway:
#    url: jdbc:postgresql://localhost:15432/task-tracker-backend
#    user: admin
#    password: admin

server:
  port: 8083

